RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        vagrant libvirt-daemon-system vagrant-libvirt \
        pipx \
        socat \
        && \
    apt-get clean

RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin PIPX_MAN_DIR=/usr/local/share/man pipx install --include-deps ansible

