RUN apt-get update && apt-get upgrade -y

RUN set -ex; \
    no_proxy= curl -sSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg; \
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy unified' >/etc/apt/sources.list.d/intel-gpu-jammy.list; \
    curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor --output /usr/share/keyrings/oneapi-archive-keyring.gpg; \
    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" >/etc/apt/sources.list.d/oneAPI.list; \
    curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg > /usr/share/keyrings/githubcli-archive-keyring.gpg; \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list

RUN set -ex; \
    apt-get update --yes; \
    apt-get install --yes build-essential clang cmake ninja-build \
        python3 python3-pip \
        opencl-c-headers ocl-icd-opencl-dev \
        level-zero level-zero-dev \
        intel-basekit \
        python3-pip python3-dev \
        cmake gcc g++ ninja-build git clang clang-format \
        gh \
        libomp-dev; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    mkdir neo; cd neo; \
    curl -OL https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17384.11/intel-igc-core_1.0.17384.11_amd64.deb; \
    curl -OL https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17384.11/intel-igc-opencl_1.0.17384.11_amd64.deb; \
    curl -OL https://github.com/intel/compute-runtime/releases/download/24.31.30508.7/intel-level-zero-gpu_1.3.30508.7_amd64.deb; \
    curl -OL https://github.com/intel/compute-runtime/releases/download/24.31.30508.7/intel-opencl-icd_24.31.30508.7_amd64.deb; \
    curl -OL https://github.com/intel/compute-runtime/releases/download/24.31.30508.7/libigdgmm12_22.4.1_amd64.deb; \
    curl -L https://github.com/intel/compute-runtime/releases/download/24.31.30508.7/ww31.sum | grep -v 'ddeb$' >ww31.sum; \
    sha256sum -c ww31.sum; dpkg -i *.deb; cd ..; rm -rf neo

RUN pip install lit numpy
