RUN set -ex; \
    curl -sSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg; \
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy max' >/etc/apt/sources.list.d/intel-gpu-jammy.list; \
    curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor --output /usr/share/keyrings/oneapi-archive-keyring.gpg; \
    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" >/etc/apt/sources.list.d/oneAPI.list; \
    apt-get update --yes; \
    apt-get install --yes build-essential clang cmake ninja-build \
        python3 python3-pip \
        intel-opencl-icd intel-level-zero-gpu clinfo intel-basekit-2024.0; \
    rm -rf /var/lib/apt/lists/*

