RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    pipx \
    snapd

RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin PIPX_MAN_DIR=/usr/local/share/man pipx install --include-deps ansible

ENV PATH=/snap/bin:"$PATH"

COPY --chown=ghrunner:ghrunner home-snap/ /home/ghrunner/snap

